redditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources(:users)
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
  resources :comments, only: [:create, :show]

  resources :posts do
    resources :comments, only: [:new]
  end

end

redditClone/app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :description, :moderator, presence: true


  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: "User"

  has_many :postsubs,
    foreign_key: :sub_id,
    class_name: "PostSub",
    dependent: :destroy,
    inverse_of: :sub

  has_many :posts,
    through: :postsubs,
    source: :post

end

redditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_logged_in, only: [:new, :create, :edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      redirect_to edit_sub_url(@sub)
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

redditClone/app/helpers/subs_helper.rb
module SubsHelper
end

redditClone/app/views/subs/edit.html.erb
<h2>Edit Sub</h2>
<form action="<%=subs_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="_method" value="PATCH">
  <label>Title:
    <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>
  <label>Description:
    <textarea name="sub[description]"><%=@sub.description%></textarea>
  </label>
  <input type="submit" value="Edit Sub">
</form>

redditClone/app/views/subs/index.html.erb
<div>
  <ul> 
<% @subs.each do |sub| %>
  <li> <a href="<%=sub_url(sub)%>"><%=sub.title%> </a></li>
<% end %>
  </ul>
</div>

<a href="<%=new_sub_url%>">New Sub</a>

redditClone/app/views/subs/new.html.erb
<h2>Create a Sub</h2>

<form class = "formblock" action="<%=subs_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Title:
    <input type="text" name="sub[title]">
  </label>
  <label>Description:
    <textarea name="sub[description]"></textarea>
  </label>
  <input type="submit" value="Create Sub">
</form>

redditClone/app/views/subs/show.html.erb
<h1><%= @sub.title%> </h1>
<%=@sub.description%>
<br>
<a href="<%=new_post_url%>">New Post</a>

<ul>
<%@sub.posts.each do |post|%>
<li><a href="<%=post_url(post)%>"><%=post.title%></a></li>
<%end%>
</ul>