redditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources(:users)
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
  resources :comments, only: [:create, :show]

  resources :posts do
    resources :comments, only: [:new]
  end

end

redditClone/app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post,
    foreign_key: :post_id,
    class_name: "Post"

  belongs_to :author,
    foreign_key: :author_id,
    class_name: "User"

  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: "Comment",
    optional: true

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: "Comment"

end

redditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end

  end

  def show
    @comment = Comment.find_by(id: params[:id])
    render :show
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :content, :parent_comment_id)
  end

end

redditClone/app/helpers/comments_helper.rb
module CommentsHelper
end

redditClone/app/views/comments/_comment.html.erb
  <%=comment.author.username%>:
  <%=comment.content%> (<a href="<%=comment_url(comment)%>">link</a>)
  

   <ul>
   <% comments_by_parent_id[comment.id].each do |child|%>
     <li><%= render partial: 'comments/comment', locals: {comment: child, comments_by_parent_id: comments_by_parent_id } %></li>
   <%end%>
   </ul>
  

redditClone/app/views/comments/new.html.erb
<h2>Add a Comment</h2>
<form action="<%=comments_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="comment[post_id]" value="<%=params[:post_id]%>">
  <label>Content:
    <textarea name="comment[content]"><%=@comment.content%></textarea>
  </label>
  <input type="submit" value="Post">
</form>

redditClone/app/views/comments/show.html.erb
  <%=@comment.author.username%>:
  <%=@comment.content%>

<h4>Reply:</h4>
<form action="<%=comments_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="comment[post_id]" value="<%=@comment.post_id%>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%=@comment.id%>">
  <label>Content:
    <textarea name="comment[content]"><%=@comment.content%></textarea>
  </label>
  <input type="submit" value="Post">
</form>