redditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources(:users)
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
  resources :comments, only: [:create, :show]

  resources :posts do
    resources :comments, only: [:new]
  end

end

redditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <header>
    <h1>reddit.clone</h1>
    <ul>
    <% if logged_in? %>
      <li><span class="greeting">Hello, <%= current_user.username %></span></li>
      <li><form class="just_button" action="<%=session_url%>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="submit" value="Sign out">
      </form></li>
    <% else %>
      <li><a href="<%=new_session_url%>">Sign In</a></li>
      <li><a href="<%=new_user_url%>">Sign Up</a></li>
    <% end %>
    </ul>
  </header>
  <div class="main-content">
  <div class="errorbar">
    <% if flash[:errors] %>
      <%flash[:errors].each do |error|%>
        <div class="error"><%=error%></div>
      <%end%>
    <%end%>
  </div>
    <%= yield %>
  </div>
  </body>
</html>