redditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources(:users)
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
  resources :comments, only: [:create, :show]

  resources :posts do
    resources :comments, only: [:new]
  end

end

redditClone/app/models/post.rb
class Post < ApplicationRecord

  belongs_to(:author, foreign_key: :author_id, class_name: :User)

  has_many :postsubs,
    foreign_key: :post_id,
    class_name: "PostSub",
    dependent: :destroy,
    inverse_of: :post

  has_many :subs,
    through: :postsubs,
    source: :sub

  has_many :comments,
    foreign_key: :post_id,
    class_name: "Comment"

  validates :title, presence: true
  validate :has_sub?

  def has_sub?
    self.subs.count > 0
  end

  def comments_by_parent_id
    commenthash = Hash.new { |h, k| h[k] = Array.new }
    self.comments.each do |comment|
      commenthash[comment.parent_comment_id] << comment
    end
    commenthash
  end

end

redditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, only: [:new, :create, :edit, :update]

  def new 
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end

  end

  def show
    @post = Post.find_by(id: params[:id])
    @all_comments = @post.comments.includes(:author)
    @toplevel = @all_comments.select { |comment| comment.parent_comment_id == nil }
    @comments_by_parent_id = @post.comments_by_parent_id
    render :show
  end

  def edit 
    @post = Post.find_by(id: params[:id])
    if @post.author_id == current_user.id
      render :edit
    else
      flash.now[:errors] = ["You can't edit someone else's post!"]
      render :show
    end
  end

  def update
    @post = Post.find_by(id: params[:id])

    if @post.author_id != current_user.id
      flash.now[:errors] = ["You can't edit someone else's post!"]
      render :show
    elsif @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end

  end

  def destroy
    @post = Post.find_by(id: params[:id])

    if @post.author_id != current_user.id
      flash.now[:errors] = ["You can't destroy someone else's post!"]
      render :show
    elsif @post.destroy
      redirect_to subs_url(Sub.find_by(id: @post.sub_id))
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to post_url(@post)
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

end

redditClone/app/helpers/posts_helper.rb
module PostsHelper
end

redditClone/app/views/posts/edit.html.erb
<h2>Edit a Post</h2>
<form action="<%=post_url(@post)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Title:
    <input type="text" name="post[title]" value="<%=@post.title%>">
  </label>
  <label>URL:
    <input type="text" name="post[url]" value="<%=@post.url%>">
  </label>
  <label>Content:
    <textarea name="post[content]"><%=@post.content%></textarea>
  </label>
  <label>Subs:
    <% Sub.all.each do |sub|%>
      <label><%= sub.title %>
        <input type="checkbox" value="<%= sub.id %>" name="post[sub_ids][]" 
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      </label>
    <%end%>
  </label>
  <input type="submit" value="Edit Post">
</form>

redditClone/app/views/posts/new.html.erb
<h2>Create a Post</h2>
<form action="<%=posts_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="post[sub_id]" value="<%=params[:sub_id]%>">
  <label>Title:
    <input type="text" name="post[title]" value="<%=@post.title%>">
  </label>
  <label>URL:
    <input type="text" name="post[url]" value="<%=@post.url%>">
  </label>
  <label>Content:
    <textarea name="post[content]"><%=@post.content%></textarea>
  </label>
  <label>Subs:
    <% Sub.all.each do |sub|%>
      <label><%= sub.title %>
        <input type="checkbox" value="<%= sub.id %>" name="post[sub_ids][]" 
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      </label>
    <%end%>
  </label>
  <input type="submit" value="Post">
</form>

redditClone/app/views/posts/show.html.erb
<h2><a href="<%=@post.url%>"><%=@post.title%></a></h2>
Author: <%=@post.author.username%>
<br>
<div><%=@post.content%></div>

<a href="<%=new_post_comment_url(@post)%>">Add Comment</a>
<ul>

<% comments_by_parent_id = @comments_by_parent_id %>
<%@comments_by_parent_id[nil].each do |comment|%> 
  <li><%= render partial: 'comments/comment', locals: {comment: comment, comments_by_parent_id: comments_by_parent_id} %></li>
<%end%> 
</ul>